name: ml_dev
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - chardet=4.0.*
  - jupyterlab=3.6.*
  - matplotlib=3.7.*
  - pandas=1.5.*
  - python=3.9.*
  - pytorch=2.0.*
  - torchtext=0.15.*
